language: java
jdk:
  - openjdk11

env:
  global:
    - CC_TEST_REPORTER_ID=ca0ba65a28462ab9f9218e560fe6a04ddd0745712f31cc8de6fb2c3eed2ffa1e
    - JACOCO_SOURCE_PATH=src/main/java

before_install:
  - chmod +x mvnw

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - "mvn clean verify"
  - "mvn sonar:sonar \
       -Dsonar.projectKey=se.chriskevin.se:microservice-spring-boot \
       -Dsonar.organization=chriskevin-github \
       -Dsonar.host.url=https://sonarcloud.io \
       -Dsonar.login=57bdffa6e9c96a19fbef0f32e41141bbbe4e6f07"

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./cc-test-reporter format-coverage target/site/jacoco/jacoco.xml --input-type jacoco
  - ./cc-test-reporter upload-coverage
