language: java
jdk:
  - oraclejdk11
  - openjdk11

env:
  global:
    - CC_TEST_REPORTER_ID=ca0ba65a28462ab9f9218e560fe6a04ddd0745712f31cc8de6fb2c3eed2ffa1e
    - JACOCO_SOURCE_PATH=src/main/java

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: "mvn clean verify"

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./cc-test-reporter format-coverage target/site/jacoco/jacoco.xml --input-type jacoco
  - ./cc-test-reporter upload-coverage
